spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168

cassandra:
  contact-points: localhost
  keyspace-name: ocds
  port: 9042

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: document-generator-consumer-group
    enable-auto-commit: false
  producer:
    retries: 5

external-endpoints:
  public-point: http://public-point:9111
  storage:
    registration: http://storage:9131
    upload: http://storage:9131

health:
  config:
    enabled: false

management:
  actuator-security:
    username: actuator
    password-hash: "{bcrypt}$2a$10$MSaYg2SejDhqgxY6DcomQeYwQRxrFXJHgdH.UOkDqBDNzHNIUSQr."

  health:
    #    diskspace:
    #      enabled: true

    db:
      enabled: true
    #    refresh:
    #      enabled: false

    defaults:
      enabled: false

  endpoint:
    health:
      show-details: always
  #    loggers:
  #      enabled: true

  endpoints:
    web:
      exposure:
        include: "health,prometheus"

#    jmx:
#      domain: com.procurement
#      exposure:
#        exclude: "*"
#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true
#      sla:
#        http:
#          server:
#            requests: 1ms,5ms
#     export:
#       jvm:
#         enabled: true
#     enable:
#       jvm: true
#  server:
#    port: 9999
#  info:
#    git:
#      mode: full
